### PR TITLE
CSS did not account for the tbody tags in the generated table

### PR DESCRIPTION
**Pull request by IceMan81**
Modified the CSS to handle the tbody tags to fix the formatting

### CODE REVIEW

**Comment by marianoguerra** [comment]
thanks!

**Comment by IceMan81** [comment]
@marianoguerra Could you update the demo on the site to use the latest code? What got me a bit confused initially was that the raw html in the demo does not have any tbody tags in it but when I used the library I always got tbody tags. And thanks for the accepting the PR.

**Comment by marianoguerra** [comment]
@IceMan81 pushed, sorry for the delay

**Comment by IceMan81** [comment]
@marianoguerra Thanks!

**Pull request merged**
